project:
  type: website
  render:
    - "*.qmd"
    - "!content-archive/"
    - "!old_website/"
    - "!quarto-*/"


website:
  title: "EKIO Academy"
  description: "R & Ciência de Dados para Economia e Análise Urbana | Plataforma Educacional Brasileira de Economia Urbana"
  site-url: "https://academy.ekio.io"

  google-analytics: "G-XXXXXXXXXX"  # To be configured

  navbar:
    background: "#1abc9c"
    foreground: white
    collapse: true
    left:
      - text: "Aprender"
        menu:
          - text: "Tutoriais"
            href: tutorials/index.qmd
          - text: "Mini Cursos"
            href: tutorials/index.qmd
          - text: "Cursos Completos"
            href: courses/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Livros"
        href: books/index.qmd
      - text: "Gráficos Semanais"
        href: weekly-charts/index.qmd
      - text: "Sobre"
        href: about.qmd
    right:
      - icon: "github"
        href: "https://github.com/viniciusoike/ekioacademy"
        aria-label: "GitHub"
      - icon: "linkedin"
        href: "https://linkedin.com/company/ekio-analytics"
        aria-label: "LinkedIn"

  search:
    type: overlay
    copy-button: true

  page-footer:
    background: "#2c3e50"
    foreground: white
    left: |
      © 2024 EKIO Academy. Parte da [EKIO](https://ekio.io).
    center: |
      Treinamento profissional em R para economistas e planejadores urbanos.
format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    highlight-style: assets/themes/material-palenight-r.theme
    css:
      - styles.css
      - assets/css/ekio-theme.css
    include-in-header: _includes/head-custom.html
    include-after-body: _includes/analytics.html

execute:
  warning: false
  message: false
  cache: true
  freeze: true
