project:
  type: website
  title: "EKIO Academy"
  
profiles:
  default:
    output-dir: _site
    website:
      site-url: "https://academy.ekio.com.br"
      
  portuguese:
    output-dir: _site-pt  
    website:
      site-url: "https://academy.ekio.com.br/pt"

website:
  title: "EKIO Academy"
  description: "R & Data Science for Economics and Urban Analysis | Brazilian Urban Economics Education Platform"
  
  google-analytics: "G-XXXXXXXXXX"  # To be configured
  
  navbar:
    logo: "assets/images/logos/ekio-academy-logo.png"
    title: false  # Hide text when logo is present
    background: "#1abc9c"  # Academy Primary color
    foreground: white
    collapse: true
    left:
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "Books" 
        href: books/index.qmd
      - text: "Courses"
        href: courses/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: "github"
        href: "https://github.com/ekio-brazil/ekio-academy"
        aria-label: "GitHub"
      - icon: "linkedin"
        href: "https://linkedin.com/company/ekio-analytics"
        aria-label: "LinkedIn"
      - text: "🇺🇸/🇧🇷"
        menu:
          - text: "🇺🇸 English"
            href: "/"
          - text: "🇧🇷 Português" 
            href: "/pt/"

  search: 
    type: overlay
    placeholder: "Search tutorials, books, courses..."
    copy-button: true

  page-footer:
    background: "#2c3e50"
    foreground: white
    left: |
      © 2024 EKIO Academy. Part of [EKIO Analytics](https://ekio.com.br).
    center: |
      Professional R training for economists and urban planners.
    right: |
      [Privacy Policy](privacy.qmd) | [Terms](terms.qmd)

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-fold: false
    code-tools: true
    highlight-style: github
    css: 
      - styles.css
      - assets/css/ekio-theme.css
    include-in-header: _includes/head-custom.html
    include-after-body: _includes/analytics.html
    
execute:
  echo: true
  warning: false
  message: false
  cache: true
  freeze: auto