project:
  type: website
  render:
    - "*.qmd"
    - "!content-archive/"
    - "!quarto-*/"


website:
  title: "EKIO Academy"
  description: "R & Data Science for Economics and Urban Analysis | Brazilian Urban Economics Education Platform"
  site-url: "https://academy.ekio.io"

  google-analytics: "G-XXXXXXXXXX"  # To be configured

  navbar:
    logo: "assets/images/logos/ekio-academy-logo.png"
    title: false  # Hide text when logo is present
    background: "#1abc9c"
    foreground: white
    collapse: true
    left:
      - text: "Mini Courses"
        menu:
          - text: "English"
            href: tutorials/index.qmd
          - text: "Português"
            href: tutorials/index-pt.qmd
      - text: "Books"
        menu:
          - text: "English"
            href: books/index.qmd
          - text: "Português"
            href: books/index-pt.qmd
      - text: "Courses"
        menu:
          - text: "English"
            href: courses/index.qmd
          - text: "Português"
            href: courses/index-pt.qmd
      - text: "Blog"
        menu:
          - text: "English"
            href: blog/index.qmd
          - text: "Português"
            href: blog/index-pt.qmd
      - text: "Research & Insights"
        href: insights/index.qmd
      - text: "Weekly Charts"
        menu:
          - text: "English"
            href: weekly-charts/index.qmd
          - text: "Português"
            href: weekly-charts/index-pt.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: "github"
        href: "https://github.com/viniciusoike/ekioacademy"
        aria-label: "GitHub"
      - icon: "linkedin"
        href: "https://linkedin.com/company/ekio-analytics"
        aria-label: "LinkedIn"

  search:
    type: overlay
    copy-button: true

  page-footer:
    background: "#2c3e50"
    foreground: white
    left: |
      © 2024 EKIO Academy. Part of [EKIO Analytics](https://ekio.io).
    center: |
      Professional R training for economists and urban planners.
    right: |
      [Privacy Policy](https://ekio.io/privacy) | [Terms](https://ekio.io/terms)

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    highlight-style: github
    css:
      - styles.css
      - assets/css/ekio-theme.css
    include-in-header: _includes/head-custom.html
    include-after-body: _includes/analytics.html

execute:
  echo: true
  warning: false
  message: false
  cache: true
  freeze: true
