[build]
  command = "npm run build"
  publish = "_combined"
  
[build.environment]
  NODE_VERSION = "18"
  R_VERSION = "4.3.2"

# Language-based redirects
[[redirects]]
  from = "/pt/*"
  to = "/pt/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com"

# Caching optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]] 
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Form handling
[forms]
  [forms."course-enrollment"]
    action = "/enrollment-success"
  [forms."contact"]
    action = "/contact-success"